name: Build Binaries

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.6
          
      - name: Install dependencies and build
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv run build

      - name: Generete artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: dist/
          if-no-files-found: error
          
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
